- name: Example Playbook
  hosts: localhost
  connection: local
  tasks:
    - name: Print URL
      vars:
        URL: Play.google.com
      ansible.builtin.debug:
        msg: Print URL - {{ URL }}

