- name: Variables
  hosts: localhost
  connection: local
  tasks:
    - name: Print Variable
      vars:
        URL: task.google.com
        ansible.builtin.debug:
          msg: Var URL - {{ URL }}
